import { defineStore } from 'pinia'

export const usePlaylistStore = defineStore('playlist', {
  state: () => ({
    playlist: [
      {
        album: {
          id: 37579301,
          name: '偶像练习生 表演曲目合集',
          picUrl:
            'https://p2.music.126.net/0fNqjjWb3srRgcsb0w7Qzg==/109951163170276615.jpg',
          tns: [],
          pic_str: '109951163170276615',
          pic: 109951163170276600,
        },
        alias: ['原唱：陈粒'],
        artists: [
          {
            id: 13058505,
            name: '周锐',
            tns: [],
            alias: [],
          },
          {
            id: 13057511,
            name: '郑艺彬',
            tns: [],
            alias: [],
          },
          {
            id: 13056454,
            name: 'ONER灵超',
            tns: [],
            alias: [],
          },
          {
            id: 12118230,
            name: '钱正昊',
            tns: [],
            alias: [],
          },
        ],
        commentThreadId: 'R_SO_4_543987400',
        copyrightId: 1377826,
        duration: 203846,
        id: 543987400,
        mvid: 0,
        name: '小半 (Live)',
        cd: '04',
        position: 5,
        ringtone: null,
        rtUrl: null,
        status: 0,
        pstatus: 0,
        fee: 0,
        version: 115,
        songType: 0,
        mst: 9,
        score: 100,
        ftype: 0,
        rtUrls: [],
        privilege: {
          id: 543987400,
          fee: 0,
          payed: 0,
          st: 0,
          pl: 320000,
          dl: 999000,
          sp: 7,
          cp: 1,
          subp: 1,
          cs: false,
          maxbr: 999000,
          fl: 320000,
          toast: false,
          flag: 256,
          preSell: false,
          playMaxbr: 999000,
          downloadMaxbr: 999000,
          maxBrLevel: 'hires',
          playMaxBrLevel: 'hires',
          downloadMaxBrLevel: 'hires',
          plLevel: 'exhigh',
          dlLevel: 'hires',
          flLevel: 'exhigh',
          rscl: 10,
          freeTrialPrivilege: {
            resConsumable: false,
            userConsumable: false,
            listenType: null,
          },
          chargeInfoList: [
            {
              rate: 128000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 0,
            },
            {
              rate: 192000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 0,
            },
            {
              rate: 320000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 0,
            },
            {
              rate: 999000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 1,
            },
            {
              rate: 1999000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 1,
            },
          ],
        },
        title: '小半 (Live)原唱：陈粒',
        source: {
          title: '单曲搜索',
          link: '/search/m/?s=%E5%B0%8F%E5%8D%8A&type=1',
          fid: '32',
          fdata: '小半',
        },
      },
      {
        album: {
          id: 136598704,
          name: '寻找．音乐精选 - 悲伤恋歌',
          picUrl:
            'https://p2.music.126.net/8X1nTV3tzafceWOC06cImg==/109951166656409453.jpg',
          tns: [],
          pic_str: '109951166656409453',
          pic: 109951166656409460,
        },
        alias: [],
        artists: [
          {
            id: 2116,
            name: '陈奕迅',
            tns: [],
            alias: [],
          },
        ],
        commentThreadId: 'R_SO_4_1897929515',
        copyrightId: 2706568,
        duration: 281773,
        id: 1897929515,
        mvid: 0,
        name: '圣诞结 (国)',
        cd: '01',
        position: 21,
        ringtone: '',
        rtUrl: null,
        status: 0,
        pstatus: 0,
        fee: 8,
        version: 4,
        songType: 0,
        mst: 9,
        score: 95,
        ftype: 0,
        rtUrls: [],
        privilege: {
          id: 1897929515,
          fee: 8,
          payed: 0,
          st: 0,
          pl: 128000,
          dl: 0,
          sp: 7,
          cp: 1,
          subp: 1,
          cs: false,
          maxbr: 999000,
          fl: 128000,
          toast: false,
          flag: 260,
          preSell: false,
          playMaxbr: 999000,
          downloadMaxbr: 999000,
          maxBrLevel: 'lossless',
          playMaxBrLevel: 'lossless',
          downloadMaxBrLevel: 'lossless',
          plLevel: 'standard',
          dlLevel: 'none',
          flLevel: 'standard',
          rscl: null,
          freeTrialPrivilege: {
            resConsumable: false,
            userConsumable: false,
            listenType: null,
          },
          chargeInfoList: [
            {
              rate: 128000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 0,
            },
            {
              rate: 192000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 1,
            },
            {
              rate: 320000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 1,
            },
            {
              rate: 999000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 1,
            },
          ],
        },
        title: '圣诞结 (国)',
        source: null,
      },
      {
        album: {
          id: 34780579,
          name: '小梦大半',
          picUrl:
            'https://p1.music.126.net/HQxTggMCB7AHUXN-ZFEtmA==/1371091013186741.jpg',
          tns: [],
          pic: 1371091013186741,
        },
        alias: [],
        artists: [
          {
            id: 1007170,
            name: '陈粒',
            tns: [],
            alias: [],
          },
        ],
        commentThreadId: 'R_SO_4_421423806',
        copyrightId: 1416476,
        duration: 297240,
        id: 421423806,
        mvid: 5350085,
        name: '小半',
        cd: '1',
        position: 3,
        ringtone: null,
        rtUrl: null,
        status: 0,
        pstatus: 0,
        fee: 8,
        version: 123,
        songType: 0,
        mst: 9,
        score: 100,
        ftype: 0,
        rtUrls: [],
        privilege: {
          id: 421423806,
          fee: 8,
          payed: 0,
          st: 0,
          pl: 128000,
          dl: 0,
          sp: 7,
          cp: 1,
          subp: 1,
          cs: false,
          maxbr: 999000,
          fl: 128000,
          toast: false,
          flag: 260,
          preSell: false,
          playMaxbr: 999000,
          downloadMaxbr: 999000,
          maxBrLevel: 'lossless',
          playMaxBrLevel: 'lossless',
          downloadMaxBrLevel: 'lossless',
          plLevel: 'standard',
          dlLevel: 'none',
          flLevel: 'standard',
          rscl: null,
          freeTrialPrivilege: {
            resConsumable: false,
            userConsumable: false,
            listenType: null,
          },
          chargeInfoList: [
            {
              rate: 128000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 0,
            },
            {
              rate: 192000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 1,
            },
            {
              rate: 320000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 1,
            },
            {
              rate: 999000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 1,
            },
          ],
        },
        title: '小半',
        source: null,
      },
      {
        duration: 198000,
        status: -1,
        ftype: 0,
        score: 100,
        copyrightId: 753020,
        mvid: 0,
        transNames: null,
        no: 12,
        commentThreadId: 'R_SO_4_30431368',
        publishTime: 0,
        type: 0,
        alias: [],
        privilege: {
          id: 30431368,
          fee: 8,
          payed: 0,
          st: 0,
          pl: 128000,
          dl: 0,
          sp: 7,
          cp: 1,
          subp: 1,
          cs: false,
          maxbr: 999000,
          fl: 128000,
          toast: false,
          flag: 260,
          preSell: false,
          playMaxbr: 999000,
          downloadMaxbr: 999000,
          maxBrLevel: 'lossless',
          playMaxBrLevel: 'lossless',
          downloadMaxBrLevel: 'lossless',
          plLevel: 'standard',
          dlLevel: 'none',
          flLevel: 'standard',
          rscl: null,
          freeTrialPrivilege: {
            resConsumable: false,
            userConsumable: false,
            listenType: null,
          },
          chargeInfoList: [
            {
              rate: 128000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 0,
            },
            {
              rate: 192000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 1,
            },
            {
              rate: 320000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 1,
            },
            {
              rate: 999000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 1,
            },
          ],
        },
        djid: 0,
        album: {
          id: 3098832,
          name: '如也',
          picUrl:
            'http://p1.music.126.net/VuJFMbXzpAProbJPoXLv7g==/7721870161993398.jpg',
          pic_str: '7721870161993398',
          pic: 7721870161993398,
        },
        artists: [
          {
            id: 1007170,
            name: '陈粒',
          },
        ],
        fee: 0,
        name: '祝星',
        id: 30431368,
        source: {
          title: '歌手',
          link: '/artist?id=1007170&_hash=songlist-30431368',
          fid: '2',
          fdata: '1007170',
        },
      },
      {
        duration: 212307,
        privilege: {
          id: 30431375,
          fee: 8,
          payed: 0,
          st: 0,
          pl: 128000,
          dl: 0,
          sp: 7,
          cp: 1,
          subp: 1,
          cs: false,
          maxbr: 999000,
          fl: 128000,
          toast: false,
          flag: 260,
          preSell: false,
          playMaxbr: 999000,
          downloadMaxbr: 999000,
          maxBrLevel: 'lossless',
          playMaxBrLevel: 'lossless',
          downloadMaxBrLevel: 'lossless',
          plLevel: 'standard',
          dlLevel: 'none',
          flLevel: 'standard',
          rscl: null,
          freeTrialPrivilege: {
            resConsumable: false,
            userConsumable: false,
            listenType: null,
          },
          chargeInfoList: [
            {
              rate: 128000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 0,
            },
            {
              rate: 192000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 1,
            },
            {
              rate: 320000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 1,
            },
            {
              rate: 999000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 1,
            },
          ],
        },
        djid: 0,
        album: {
          id: 3098832,
          name: '如也',
          picUrl:
            'http://p2.music.126.net/VuJFMbXzpAProbJPoXLv7g==/7721870161993398.jpg',
          pic_str: '7721870161993398',
          pic: 7721870161993398,
        },
        artists: [
          {
            id: 1007170,
            name: '陈粒',
          },
        ],
        fee: 0,
        alias: [],
        type: 0,
        status: -1,
        score: 100,
        copyrightId: 753020,
        mvid: 0,
        transNames: null,
        no: 4,
        commentThreadId: 'R_SO_4_30431375',
        publishTime: 0,
        ftype: 0,
        name: '历历万乡',
        id: 30431375,
        source: {
          title: '歌手',
          link: '/artist?id=1007170&_hash=songlist-30431375',
          fid: '2',
          fdata: '1007170',
        },
      },
      {
        album: {
          id: 71893789,
          name: 'Again',
          picUrl:
            'https://p1.music.126.net/-gqv2SAG4MMD2ZE-hj53yg==/109951163415566764.jpg',
          tns: [],
          pic_str: '109951163415566764',
          pic: 109951163415566770,
        },
        alias: ['纸性恋'],
        artists: [
          {
            id: 1142011,
            name: '王极',
            tns: [],
            alias: [],
          },
        ],
        commentThreadId: 'R_SO_4_1295009639',
        copyrightId: 0,
        duration: 122207,
        id: 1295009639,
        mvid: 0,
        name: 'Again',
        cd: '01',
        position: 1,
        ringtone: null,
        rtUrl: null,
        status: 0,
        pstatus: 0,
        fee: 8,
        version: 17,
        songType: 0,
        mst: 9,
        score: 100,
        ftype: 0,
        rtUrls: [],
        privilege: {
          id: 1295009639,
          fee: 8,
          payed: 0,
          st: 0,
          pl: 128000,
          dl: 0,
          sp: 7,
          cp: 1,
          subp: 1,
          cs: false,
          maxbr: 999000,
          fl: 128000,
          toast: false,
          flag: 6,
          preSell: false,
          playMaxbr: 999000,
          downloadMaxbr: 999000,
          maxBrLevel: 'lossless',
          playMaxBrLevel: 'lossless',
          downloadMaxBrLevel: 'lossless',
          plLevel: 'standard',
          dlLevel: 'none',
          flLevel: 'standard',
          rscl: null,
          freeTrialPrivilege: {
            resConsumable: false,
            userConsumable: false,
            listenType: null,
          },
          chargeInfoList: [
            {
              rate: 128000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 0,
            },
            {
              rate: 192000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 1,
            },
            {
              rate: 320000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 1,
            },
            {
              rate: 999000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 1,
            },
          ],
        },
        title: 'Again纸性恋',
        source: null,
      },
      {
        album: {
          id: 15238,
          name: '跨越.新天堂(精华典藏版)',
          picUrl:
            'https://p2.music.126.net/_2-mfxIGGnt5KJh4cE7qJQ==/745468883644326.jpg',
          tns: [],
          pic: 745468883644326,
        },
        alias: [],
        artists: [
          {
            id: 5198,
            name: '腾格尔',
            tns: [],
            alias: [],
          },
        ],
        commentThreadId: 'R_SO_4_151200',
        copyrightId: 22019,
        duration: 460000,
        id: 151200,
        mvid: 0,
        name: '天堂',
        cd: '1',
        position: 13,
        ringtone: '600902000007913837',
        rtUrl: null,
        status: 0,
        pstatus: 0,
        fee: 8,
        version: 15,
        songType: 0,
        mst: 9,
        score: 100,
        ftype: 0,
        rtUrls: [],
        privilege: {
          id: 151200,
          fee: 8,
          payed: 0,
          st: 0,
          pl: 128000,
          dl: 0,
          sp: 7,
          cp: 1,
          subp: 1,
          cs: false,
          maxbr: 320000,
          fl: 128000,
          toast: false,
          flag: 262,
          preSell: false,
          playMaxbr: 320000,
          downloadMaxbr: 320000,
          maxBrLevel: 'exhigh',
          playMaxBrLevel: 'exhigh',
          downloadMaxBrLevel: 'exhigh',
          plLevel: 'standard',
          dlLevel: 'none',
          flLevel: 'standard',
          rscl: null,
          freeTrialPrivilege: {
            resConsumable: false,
            userConsumable: false,
            listenType: null,
          },
          chargeInfoList: [
            {
              rate: 128000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 0,
            },
            {
              rate: 192000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 1,
            },
            {
              rate: 320000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 1,
            },
            {
              rate: 999000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 1,
            },
          ],
        },
        title: '天堂',
        source: null,
      },
      {
        album: {
          id: 3064113,
          name: '匆匆那年',
          picUrl:
            'https://p2.music.126.net/yXyeAl-7m0tqfx4AX7BDSQ==/2542070884980240.jpg',
          tns: [],
          pic: 2542070884980240,
        },
        alias: ['电影《匆匆那年》同名主题曲'],
        artists: [
          {
            id: 9621,
            name: '王菲',
            tns: [],
            alias: [],
          },
        ],
        commentThreadId: 'R_SO_4_29713754',
        copyrightId: 600011,
        duration: 240991,
        id: 29713754,
        mvid: 358005,
        name: '匆匆那年',
        cd: '1',
        position: 1,
        ringtone: null,
        rtUrl: null,
        status: 0,
        pstatus: 0,
        fee: 1,
        version: 59,
        songType: 0,
        mst: 9,
        score: 100,
        ftype: 0,
        rtUrls: [],
        transNames: ['Fleet of Time'],
        privilege: {
          id: 29713754,
          fee: 1,
          payed: 1,
          st: 0,
          pl: 999000,
          dl: 999000,
          sp: 7,
          cp: 1,
          subp: 1,
          cs: false,
          maxbr: 999000,
          fl: 0,
          toast: false,
          flag: 260,
          preSell: false,
          playMaxbr: 999000,
          downloadMaxbr: 999000,
          maxBrLevel: 'lossless',
          playMaxBrLevel: 'lossless',
          downloadMaxBrLevel: 'lossless',
          plLevel: 'lossless',
          dlLevel: 'lossless',
          flLevel: 'none',
          rscl: null,
          freeTrialPrivilege: {
            resConsumable: false,
            userConsumable: false,
            listenType: null,
          },
          chargeInfoList: [
            {
              rate: 128000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 1,
            },
            {
              rate: 192000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 1,
            },
            {
              rate: 320000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 1,
            },
            {
              rate: 999000,
              chargeUrl: null,
              chargeMessage: null,
              chargeType: 1,
            },
          ],
        },
        title: '匆匆那年电影《匆匆那年》同名主题曲',
        source: null,
      },
    ],
    currentSongId: <number>543987400,
  }),
  getters: {
    currentSong: (state) => {
      return state.playlist.find((p) => p.id === state.currentSongId)
    },
  },
})
